---
- name:  Check whether SNMP community is configured on devices. Report missing communities
  hosts: all
  tasks:
  - include_tasks: "{{item}}"
    with_fileglob: [ "tests/*.yml" ]
    ignore_errors: true
